# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-22 21:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_comment_commentmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessageManager',
        ),
    ]
