# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-23 01:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_delete_messagemanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentManager',
        ),
    ]
